apiVersion: apps/v1
kind: Deployment
metadata:
  name: websitedeployment
  labels:
    app: webpage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webpage
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template: 
    metadata: 
      labels: 
        app: webpage
    spec: 
      containers:
      - name: webpage
        image: shivap95/webpage:0.6
        ports:
        - containerPort: 8080        
        
