apiVersion: v1
kind: Service
metadata:
  name: websiteservice
  labels:
    app: webpage
spec:
  selector:
    app: webpage
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31200
   
