apiVersion: v1
kind: Service
metadata:
  name: websiteservice
  labels:
    app: jenkins0
spec:
  selector:
    app: jenkins0
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 31200
  type: LoadBalancer   
